routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('register',
    \App\Livewire\Pages\Register::class)
    ->middleware('guest')
    ->name('register');

Route::get('/',
    \App\Livewire\Pages\Index::class)
    ->name('index');

// ------------- Ganjizade ------------- //

Route::get('/traveller',
    \App\Livewire\Pages\Flight\Traveller::class)
    ->middleware('auth')
    ->name('traveller');

Route::get('/checkout',
    \App\Livewire\Pages\Flight\Checkout::class)
    ->middleware('auth')
    ->name('checkout');

Route::get('/hotel/{id}/{slug}',
    \App\Livewire\Pages\Hotel\Reservation::class)
    ->name('hotel.show');

Route::get('/hotel/book',
    \App\Livewire\Pages\Hotel\Book::class)
    ->name('hotel.book');

// ------------- Ganjizade ------------- //

Route::name('hotel.')
    ->group(function () {
        Route::get('hotels',
            \App\Livewire\HotelSearch::class)
            ->name('index');
    });

app/Livewire/Components/FlightCardItem.php
<?php

namespace App\Livewire\Components;

use App\Repository\TravelRepositoryInterface;
use Livewire\Component;

class FlightCardItem extends Component
{
    public $flight_id;
    public $travel;
    private TravelRepositoryInterface $travelRepository;

    public function boot(TravelRepositoryInterface $travelRepository)
    {
        $this->travelRepository = $travelRepository;
    }
    public function flight_detail()
    {
        $this->travel = $this->travelRepository->create([
            'flight_id' => $this->flight_id,
            'user_id'   => 1,
        ]);
        return redirect(url('/traveller' . '?flight_id=' . $this->flight_id . '&travel_id=' . $this->travel->id . '&child=1&adult=2'));
    }
    public function render()
    {
        return view('livewire.components.flight-card-item');
    }
}

app/Livewire/Components/FlightSearch.php
<?php

namespace App\Livewire\Components;

use App\Models\City;
use Filament\Forms\Components;
use Filament\Forms\Components\Select;
use Livewire\Attributes\Url;
use Livewire\Component;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\MarkdownEditor;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Illuminate\Contracts\View\View;


class FlightSearch extends Component implements HasForms
{
    use InteractsWithForms;

    public ?array $data = [];
    #[Url]
    public $ticket_class;
    #[Url]
    public $adult_passengers;
    #[Url]
    public $children_passengers;
    #[Url]
    public $from;
    #[Url]
    public $to;
    #[Url]
    public $date;

    public function mount(): void
    {
        $this->form->fill();
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Components\Grid::make(3)->schema([
                    Select::make('ticket_class')
                        ->required()
                        ->default($this->ticket_class)
//                        TODO
                        ->options([
                            'economy' => 'Economy',
                            'business' => 'Business',
                            'first_class' => 'First Class',
                        ]),

                    TextInput::make('adult_passengers')
                        ->required()
                        ->default($this->adult_passengers)
                        ->integer()
                        ->minValue(1)
                        ->default(1),

                    TextInput::make('children_passengers')
                        ->default($this->children_passengers)
                        ->required()
                        ->integer()
                        ->minValue(0)
                        ->default(0),
                ]),
                Components\Grid::make(3)->schema([
                    Select::make('from')
                        ->required()
                        ->searchable()
                        ->getSearchResultsUsing(fn(string $search): array => City::where('name', 'like', "%{$search}%")
                            ->orderBy('name')
                            ->limit(50)
                            ->pluck('name', 'id')->toArray()),
                    Select::make('to')
                        ->required()
                        ->searchable()
                        ->getSearchResultsUsing(fn(string $search): array => City::where('name', 'like', "%{$search}%")
                            ->orderBy('name')
                            ->limit(50)
                            ->pluck('name', 'id'
                            )->toArray()),
                    Components\DatePicker::make('date')
                        ->default($this->date)
                        ->required()
                        ->minDate(now())
                        ->maxDate(now()->addYear())

                ]),

            ])
            ->statePath('data');
    }

    public function search(): void
    {
//ticket_class
//adult_passengers
//children_passengers
//from
//to
//date
        $this->redirectRoute('index', $this->form->getState());
//        dd($this->form->getState());

    }

    public function render()
    {
        return view('livewire.components.flight-search');
    }
}

app/Livewire/Components/FlightSearchResult.php
<?php

namespace App\Livewire\Components;

use App\Models\Flight;
use App\Repository\Eloquent\FlightRepository;
use App\Repository\FlightRepositoryInterface;
use Livewire\Attributes\Url;
use Livewire\Component;

class FlightSearchResult extends Component
{

    #[Url]
    public $ticket_class;
    #[Url]
    public $adult_passengers;
    #[Url]
    public $children_passengers;
    #[Url]
    public $from;
    #[Url]
    public $to;
    #[Url]
    public $date;

    public $flights;

    public function mount()
    {


//        $receivedData = [
//            $this->ticket_class,
//            $this->adult_passengers,
//            $this->children_passengers,
//            $this->from,
//            $this->to,
//            $this->date,
//        ];
//        dump($receivedData);

        if (in_array(null, [
            $this->ticket_class,
            $this->adult_passengers,
            $this->children_passengers,
            $this->from,
            $this->to,
            $this->date,
        ], true)) {
            return;
        }
        $flightRepository = new FlightRepository(new Flight);
        $searchData = [
            'origin' => $this->from,
            'destination' => $this->to,
            'departure_date' => $this->date,
            'number_of_seats' => $this->adult_passengers + $this->children_passengers,
            'cabin_type' => $this->ticket_class,
        ];
//        $searchData = [
//            'origin' => 61800,
//            'destination' => 61800,
//            'departure_date' => '2023-08-20',
//            'number_of_seats' => 1,
//            'cabin_type' => 'economy',
//        ];
        
    $this->flights = $flightRepository->search($searchData);

    }

    public function render()
    {
        return view('livewire.components.flight-search-result');
    }
}

app/Livewire/Components/Header.php
<?php

namespace App\Livewire\Components;

use Livewire\Component;

class Header extends Component
{
    public function render()
    {
        return view('livewire.components.header');
    }
}

app/Livewire/Components/TravelPrice.php
<?php

namespace App\Livewire\Components;

use App\Models\Baggage;
use Livewire\Attributes\On;
use Livewire\Component;

class TravelPrice extends Component
{
    public $travel;
    public $travellers = [];
    public $price;

    public function mount()
    {
        //---------------- Calculate Price of Travel ----------------//
        $this->price = $this->travel->calculate_travel_price($this->travellers);
    }

    #[On('baggageAdded')]
    public function baggageAdded($baggage_id)
    {
        $baggage = Baggage::where('id', $baggage_id)->pluck('price')->first();
        $this->price['baggage'] += (int) $baggage;
        $this->price['total'] += (int) $baggage;
    }

    #[On('baggageRemoved')]
    public function baggageRemoved($baggage_id)
    {
        $baggage = Baggage::where('id', $baggage_id)->pluck('price')->first();
        $this->price['baggage'] -= (int) $baggage;
        $this->price['total'] -= (int) $baggage;
    }

    public function render()
    {
        return view('livewire.components.travel-price');
    }
}

app/Livewire/Flights/Search.php
<?php

namespace App\Livewire\Flights;

use Illuminate\Support\Facades\Http;
use Livewire\Component;
use GuzzleHttp\Client;

class Search extends Component
{
    public $origin = 'test1';
    public $destination = 'test2';
    public $date;
    public $traveller_count;


    public $data;
    public $result;

    public function mount()
    {
        $data = [
            'origin' => $this->origin,
            'destination' => $this->destination,
            'date' => date('Y-m-d'),
            'traveller_count' => rand(1,9)
        ];

        $flights = resolve('flights');
        $response = $flights->searchInFlights($data);

        if ($response->successful()) {
            // Success
            $this->result = $response->json();
        } else {
            // Failed
            dd('failed');
        }
    }

    public function search()
    {
        $data = [
            'origin' => $this->origin,
            'destination' => $this->destination,
            'date' => date('Y-m-d'),
            'traveller_count' => rand(1,9)
        ];

        $response = Http::post('localhost/api/search', $data);

        if ($response->successful()) {
            // Success
            $this->result = $response->json();
        } else {
            // Failed
            dd('failed');
        }
    }

    public function render()
    {
        return view('livewire.flights.search');
    }
}

app/Livewire/HotelSearch.php
<?php

namespace App\Livewire;

use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Livewire\Component;

class HotelSearch extends Component implements HasForms
{
    use InteractsWithForms;


    public ?array $data = [];

    public function mount(): void
    {
        $this->form->fill();
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([

                Select::make('destination')
                    ->required()
                    ->searchable()
                    ->options(['azsd', 'asd']),

                DatePicker::make('check_in')
                    ->minDate(now())
                    ->maxDate(now()->addYear()),
                DatePicker::make('check_out')
                    ->minDate(now()->addDay())
                    ->maxDate(now()->addYear()),

                TextInput::make('adults')
                    ->required()
                    ->integer()
                    ->minValue(1)
                    ->maxValue(30)
                    ->default(1),
                TextInput::make('children')
                    ->required()
                    ->integer()
                    ->minValue(0)
                    ->maxValue(20)
                    ->default(0),
                TextInput::make('rooms')
                    ->required()
                    ->integer()
                    ->minValue(1)
                    ->maxValue(30)
                    ->default(1),
            ])->columns(3);
    }

    public function search(): void
    {
        dd($this->form->getState());
    }


    public function render()
    {
        return view('livewire.hotel-search');
    }

}

app/Livewire/Pages/Flight/Checkout.php
<?php

namespace App\Livewire\Pages\Flight;

use App\Repository\AirlineRepositoryInterface;
use App\Repository\AirportRepositoryInterface;
use App\Repository\FlightRepositoryInterface;
use App\Repository\TicketRepositoryInterface;
use App\Repository\TravelRepositoryInterface;
use Livewire\Component;

class Checkout extends Component
{
    public $user;
    public $travel;
    public $flight;
    public $airline;
    public $price;
    public $tickets;
    public $origin_city;
    public $destination_city;
    public $origin_airport;
    public $destination_airport;
    private TicketRepositoryInterface $ticketRepository;
    private TravelRepositoryInterface $travelRepository;
    private FlightRepositoryInterface $flightRepository;
    private AirlineRepositoryInterface $airlineRepository;
    private AirportRepositoryInterface $airportRepository;

    public function boot(TicketRepositoryInterface $ticketRepository, TravelRepositoryInterface $travelRepository, FlightRepositoryInterface $flightRepository, AirlineRepositoryInterface $airlineRepository, AirportRepositoryInterface $airportRepository)
    {
        $this->ticketRepository = $ticketRepository;
        $this->travelRepository = $travelRepository;
        $this->flightRepository = $flightRepository;
        $this->airlineRepository = $airlineRepository;
        $this->airportRepository = $airportRepository;
    }

    public function mount()
    {
        $this->user = auth()->user();
        $this->travel = $this->travelRepository->getLastTravelOfUser($this->user->id);
        $this->flight = $this->flightRepository->findById($this->travel->flight_id);
        $this->airline = $this->airlineRepository->findById($this->flight->airline_id);
        $this->tickets = $this->ticketRepository->getTicketsOfTravel($this->travel->id);
        $this->origin_airport = $this->flight->airport_origin;
        $this->destination_airport = $this->flight->airport_destination;
        $this->origin_city = $this->flightRepository->findOriginCity($this->flight);
        $this->destination_city = $this->flightRepository->findDestinationCity($this->flight);
    }

    public function render()
    {
        return view('livewire.pages.flight.checkout');
    }
}

app/Livewire/Pages/Hotel/Book.php
<?php

namespace App\Livewire\Pages\Hotel;

use Livewire\Component;

class Book extends Component
{
    public function render()
    {
        return view('livewire.pages.hotel.book');
    }
}

app/Livewire/Pages/Hotel/Reservation.php
<?php

namespace App\Livewire\Pages\Hotel;

use Livewire\Component;

class Reservation extends Component
{
    public function render()
    {
        return view('livewire.pages.hotel.reservation');
    }
}

app/Livewire/Pages/Index.php
<?php

namespace App\Livewire\Pages;

use Livewire\Component;

class Index extends Component
{
    public function render()
    {
        return view('livewire.pages.index');
    }
}

app/Livewire/Pages/Register.php
<?php

namespace App\Livewire\Pages;

use App\Enums\Role;
use App\Models\User;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Wizard;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Illuminate\Support\Facades\Hash;
use Livewire\Component;

class Register extends Component implements HasForms
{
    use InteractsWithForms;

    public ?array $data = [];
    public string $first_name;
    public string $last_name;
    public string $email;
    public string $password;

    public function mount()
    {
//        $this->form->fill();
    }

    protected function getFormStatePath(): string
    {
        return 'data';
    }

    protected function getFormSchema(): array
    {
        return [

            TextInput::make('first_name')
                ->required()
                ->maxLength(50),
            TextInput::make('last_name')
                ->required()
                ->maxLength(50),

            TextInput::make('email')
                ->label('Email Address')
                ->email()
                ->required()
                ->maxLength(50)
                ->unique(User::class),

            TextInput::make('password')
                ->label('Password')
                ->password()
                ->required()
                ->maxLength(50)
                ->minLength(6)
                ->same('password_confirmation')
                ->confirmed()
                ->dehydrateStateUsing(fn($state) => Hash::make($state)),

            TextInput::make('password_confirmation')
                ->label('Confirm Password')
                ->password()
                ->required()
                ->maxLength(50)
                ->minLength(6)
                ->dehydrated(false),

        ];
    }

    public function register()
    {
        $user = User::create($this->form->getState());
        $user->assignRole(Role::CLIENT->value);
        auth()->login($user);
        $this->redirectRoute('index');
    }

    public function render()
    {
        return view('livewire.pages.register');
    }
}

resources/views/livewire/components/flight-card-item.blade.php
<div>

    <div class="w-full content-center text-center md:w-8/12 mx-auto shadow-smx ">
        <div class="flex border rounded-lg px-5x py-5x ">

            <div class="flex flex-1 px-4">
                {{-- Agency --}}
                <div class="my-auto text-center items-center justify-center flex flex-col ">
                    <img src="https://random.imagecdn.app/50/50" class="w-12 h-12 rounded justify-center"
                         alt="">
                    <span class="text-sm justify-center"> Agency </span>
                </div>
                {{-- /Agency --}}
                {{-- time --}}
                <div class="flex  mx-auto pt-2">
                    <div class="text-right mr-4">
                        <div class="font-bold text-lg">5:13
                            <span class="text-xs font-lightx ">PM</span></div>
                        <div class="">FAR</div>
                    </div>
                    <div class=" hidden sm:block">
                        <div class="">_______________</div>
                        <span class="mx-auto text-gray-400 text-sm">12h 24m</span>
                    </div>

                    <div class="text-left ml-4">
                        <div class="font-bold text-lg">5:13
                            <span class="text-xs font-lightx ">AM</span></div>
                        <div class="">FAR</div>
                    </div>
                </div>
                {{-- /time --}}

                {{-- separator --}}
                <div class="h-fullx bg-gray-200 w-[.5px]"></div>
                {{-- /separator --}}

                <div class="flex flex-col w-1/6 p-4x m-2">
                    <div class="text-right font-bold pr-3">$23</div>
                    <div class="text-left text-sm pl-3 pb-2">
                        Airport
                    </div>
                    <div wire:click="flight_detail" class="rounded bg-[#006ce4] hover:bg-[#003b95] mx-3
                         text-white shadow mb-2 py-0.5 cursor-pointer px-0.5">
                        View details
                    </div>
                </div>


            </div>

        </div>
    </div>

</div>

resources/views/livewire/components/flight-search-result.blade.php
<div>
    {{-- The best athlete wants his opponent at his best. --}}
</div>

resources/views/livewire/components/flight-search.blade.php
<div class="">
    <div class="bg-gray-100">
        <div class="container mx-auto py-5">
            <form wire:submit.prevent="search" class="lg:flex   flex-col items-center content-center justify-center">
                <div class="mx-auto">
                    {{ $this->form }}
                </div>
                <div class="mx-auto content-center text-center mt-4">
                    <button type="submit" class="justify mr-auto  mx-auto
        border rounded px-5 py-2 bg-[#006ce4] text-white hover:bg-[#003b95]
        text-sm font-semibold shadow-sm ring-1 ring-insetx ring-gray-300">
                        Search
                    </button>
                </div>
            </form>
        </div>

    </div>
    <div class="flex flex-col container mx-auto mt-5 gap-2">
        {{-- TODO --}}

        @for($i=0;$i<=20;$i++)
            <livewire:components.flight-card-item :flight_id="$i + 1" />
        @endfor
    </div>
</div>

resources/views/livewire/components/header.blade.php
<div class="bg-[#003B95] w-full">
    <div class="lg:flex lg:items-center lg:justify-between pt-6 pb-6 pr-6 pl-6 container mx-auto">
        <div class="min-w-0 flex-1">
            <h2 class="text-2xl font-bold leading-7 text-gray-900s
             sm:truncate sm:text-3xl sm:tracking-tight text-white">
                Booking.com
            </h2>

        </div>
        @if(!auth()->check())
            <div class="mt-5 flex lg:ml-4 lg:mt-0">
            <span class="hidden sm:block">
              <a href="{{ route('register') }}"
                 class="btn inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                 style="color: #006ec4; border-color: rgb(0, 108, 228);">
                Register
              </a>
            </span>

                <span class="ml-3 hidden sm:block">
              <a href="{{ route('filament.client.auth.login') }}"
                 class="btn inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                 style="color: #006ce4; border-color: rgb(0, 108, 228);">
                Sign In
              </a>
            </span>

                <!-- Dropdown -->
                <div class="relative ml-3 sm:hidden">
                    <button type="button"
                            class="inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:ring-gray-400"
                            id="mobile-menu-button" aria-expanded="false" aria-haspopup="true">
                        More
                        <svg class="-mr-1 ml-1.5 h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor"
                             aria-hidden="true">
                            <path fill-rule="evenodd"
                                  d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z"
                                  clip-rule="evenodd"/>
                        </svg>
                    </button>
                    <div
                        class="absolute right-0 z-10 -mr-1 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none"
                        role="menu" aria-orientation="vertical" aria-labelledby="mobile-menu-button" tabindex="-1">
                        <!-- Active: "bg-gray-100", Not Active: "" -->
                        <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1"
                           id="mobile-menu-item-0">Register</a>
                        <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1"
                           id="mobile-menu-item-1">Sign In</a>
                    </div>
                </div>
            </div>
        @else
            <div class="mt-5 flex lg:ml-4 lg:mt-0">
            <span class="hiddens sm:block">
              <a href="{{route('filament.client.pages.dashboard')}}"
                 class="btn inline-flex items-center rounded-md bg-white px-3 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50"
                 style="color: #006ec4; border-color: rgb(0, 108, 228);">
                Enter to my profile
              </a>
            </span>

            </div>
        @endif
    </div>
    {{-- navigation-bar --}}
    <div class="  flex text-white container mx-auto  gap-1 pb-3">

        <a href="{{route('index')}}"
           class=" flex rounded-full py-2 px-3 cursor-pointer text-white gap-1
        hover:bg-[#1a4fa0] text-decoration-none
        {{request()->routeIs('index')?'border-white border bg-[#1a4fa0]':''}}">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                 stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5"/>
            </svg>

            <span>
                Flights
            </span>


        </a>

        <a href="{{route('hotel.index')}}"

           class=" flex  rounded-full py-2 px-3 cursor-pointer text-white gap-1
        hover:bg-[#1a4fa0] text-decoration-none
        {{request()->routeIs('hotel.*')?'border-white border bg-[#1a4fa0]':''}}">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                 stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round"
                      d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25"/>
            </svg>
            <span>
                Hotel
            </span>


        </a>
    </div>
    {{-- /navigation-bar --}}
</div>

resources/views/livewire/components/travel-price.blade.php
<div class="col-md-4">
    <div class="card tickets-price">
        <div class="card-body">
            <div class="row">
                <div class="col-md-8"><b>Tickets (1 adult, 1 children)</b></div>
                <div class="col-md-4 text-right">{{ $price['fair'] }} €</div>
            </div>
            @if($price['baggage'] and $price['baggage'] != 0)
                <div class="row">
                    <div class="col-md-8">Baggage</div>
                    <div class="col-md-4 text-right">{{ $price['baggage'] }} €</div>
                </div>
            @endif
            <div class="row">
                <div class="col-md-8">Taxes and charges</div>
                <div class="col-md-4 text-right">{{ $price['taxes'] }} €</div>
            </div>
            <div class="row total-price">
                <div class="col-md-8">Total</div>
                <div class="col-md-4 text-right">{{ $price['total'] }} €</div>
            </div>
        </div>
    </div>
</div>